# Generated by Django 5.2.8 on 2025-12-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether user has completed onboarding'),
        ),
    ]
