# Generated by Django 5.2.8 on 2025-11-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='prescription_image',
            field=models.ImageField(blank=True, help_text='Photo of prescription if available', null=True, upload_to='prescriptions/%Y/%m/%d/'),
        ),
    ]
