# Generated by Django 5.2.8 on 2025-11-28 18:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0002_alter_familymemberaccess_family_member'),
        ('health_records', '0002_medication_prescription_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-assessment_date', '-symptom_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='clinician_name',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='findings',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='notes',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_date',
            field=models.DateField(blank=True, help_text='Date of the assessment (added by practitioner)', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='clinician',
            field=models.ForeignKey(blank=True, help_text='Clinician who added the objective assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='clinicians.clinician'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='condition_progression',
            field=models.TextField(blank=True, help_text='How the condition has progressed over time'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='current_symptoms',
            field=models.TextField(blank=True, help_text='Current symptoms described by the patient'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='objective_findings',
            field=models.TextField(blank=True, help_text='Objective clinical findings and observations (added by practitioner)'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pain_level',
            field=models.IntegerField(blank=True, help_text='Pain level from 0-10 (0 = no pain, 10 = worst pain)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='assessment',
            name='practitioner_notes',
            field=models.TextField(blank=True, help_text='Additional notes from practitioner'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='previous_symptoms',
            field=models.TextField(blank=True, help_text='Previous symptoms that have resolved or changed'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='symptom_date',
            field=models.DateField(blank=True, help_text='Date when symptoms were recorded', null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(blank=True, choices=[('physiotherapy', 'Physiotherapy'), ('general', 'General Health Check'), ('specialist', 'Specialist Consultation'), ('emergency', 'Emergency Visit'), ('other', 'Other')], help_text='Type of assessment (added by practitioner)', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='treatment_plan',
            field=models.TextField(blank=True, help_text='Treatment plan (added by practitioner)'),
        ),
    ]
