# Generated by Django 5.2.8 on 2025-11-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0003_alter_assessment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='practitioner_notes_image',
            field=models.ImageField(blank=True, help_text="Photo of practitioner's notes if available", null=True, upload_to='practitioner_notes/%Y/%m/%d/'),
        ),
    ]
