# Generated by Django 5.2.8 on 2025-11-29 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0004_assessment_practitioner_notes_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Job title or role', max_length=200)),
                ('employer', models.CharField(blank=True, help_text='Employer or company name', max_length=200)),
                ('start_date', models.DateField(help_text='Start date of this work')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if current job)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Is this your current job?')),
                ('activities', models.JSONField(default=list, help_text='List of work activities (selected from choices)')),
                ('hours_per_week', models.IntegerField(blank=True, help_text='Average hours worked per week', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about work duties and environment')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this work history')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Work Histories',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
    ]
