# Generated by Django 5.2.8 on 2025-11-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0005_workhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the assessment was completed by the practitioner', null=True),
        ),
    ]
