# Generated by Django 5.2.8 on 2025-12-19 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0007_patientclinicianaccess_consent_allergies_and_more'),
        ('health_records', '0006_assessment_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedFindings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('assessment', 'Assessment'), ('diagnosis', 'Diagnosis'), ('treatment', 'Treatment'), ('prognosis', 'Prognosis'), ('recommendations', 'Recommendations'), ('measurements', 'Measurements'), ('symptoms', 'Symptoms'), ('general', 'General')], default='general', help_text='Category of the finding', max_length=50)),
                ('finding_type', models.CharField(choices=[('measurement', 'Measurement'), ('strength', 'Strength'), ('symptom', 'Symptom'), ('treatment', 'Treatment'), ('observation', 'Observation')], default='observation', help_text='Type of finding', max_length=50)),
                ('text', models.TextField(help_text='Extracted text of the finding')),
                ('raw_extraction_data', models.JSONField(blank=True, help_text='Raw data from Azure Document Intelligence', null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True, help_text='When the finding was extracted')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the finding has been verified by a clinician')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the finding was verified', null=True)),
                ('assessment', models.ForeignKey(help_text='Assessment this finding belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='extracted_findings', to='health_records.assessment')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Clinician who verified this finding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_findings', to='clinicians.clinician')),
            ],
            options={
                'verbose_name_plural': 'Extracted Findings',
                'ordering': ['-extracted_at', 'category'],
            },
        ),
    ]
