# Generated by Django 5.2.8 on 2025-12-19 21:42

import health_records.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0007_extractedfindings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='practitioner_notes_image',
            field=models.ImageField(blank=True, help_text="Photo of practitioner's notes if available", null=True, upload_to='practitioner_notes/%Y/%m/%d/', validators=[health_records.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='medication',
            name='prescription_image',
            field=models.ImageField(blank=True, help_text='Photo of prescription if available', null=True, upload_to='prescriptions/%Y/%m/%d/', validators=[health_records.validators.validate_image_file]),
        ),
    ]
