# Generated by Django 5.2.8 on 2025-11-27 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('dr', 'Dr.'), ('nurse', 'Nurse'), ('physiotherapist', 'Physiotherapist'), ('paramedic', 'Paramedic'), ('specialist', 'Specialist'), ('other', 'Other')], default='dr', max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('speciality', models.CharField(blank=True, max_length=200)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Link to a User account if the clinician has login access', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMemberAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse/Partner'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('caregiver', 'Caregiver'), ('other', 'Other')], max_length=50)),
                ('access_level', models.CharField(choices=[('full', 'Full Access'), ('read_only', 'Read Only'), ('emergency', 'Emergency Only')], default='read_only', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for temporary access', null=True)),
                ('notes', models.TextField(blank=True)),
                ('family_member', models.ForeignKey(help_text='The family member/caregiver who has access', on_delete=django.db.models.deletion.CASCADE, related_name='patient_accesses', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='The patient whose records are being shared', on_delete=django.db.models.deletion.CASCADE, related_name='family_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Family Member Accesses',
                'ordering': ['-granted_at'],
                'unique_together': {('patient', 'family_member')},
            },
        ),
        migrations.CreateModel(
            name='PatientClinicianAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('full', 'Full Access'), ('read_only', 'Read Only'), ('emergency', 'Emergency Only')], default='read_only', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for temporary access', null=True)),
                ('notes', models.TextField(blank=True)),
                ('access_granted_by', models.ForeignKey(help_text='The user who granted this access (usually the patient or their family member)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('clinician', models.ForeignKey(help_text='The clinician who has access', on_delete=django.db.models.deletion.CASCADE, related_name='patient_accesses', to='clinicians.clinician')),
                ('patient', models.ForeignKey(help_text='The patient whose records are being shared', on_delete=django.db.models.deletion.CASCADE, related_name='clinician_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patient Clinician Accesses',
                'ordering': ['-granted_at'],
                'unique_together': {('patient', 'clinician')},
            },
        ),
    ]
