# Generated by Django 5.2.8 on 2025-11-27 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymemberaccess',
            name='family_member',
            field=models.ForeignKey(help_text='The family member/caregiver who has access', on_delete=django.db.models.deletion.CASCADE, related_name='family_member_accesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
