# Generated by Django 5.2.8 on 2025-11-29 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0002_alter_familymemberaccess_family_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(help_text='The healthcare organisation (not individual HCP name)', max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Overall rating (1-5)')),
                ('feedback_type', models.CharField(choices=[('communication', 'Communication'), ('care_quality', 'Quality of Care'), ('waiting_time', 'Waiting Times'), ('facilities', 'Facilities'), ('overall', 'Overall Experience'), ('other', 'Other')], default='overall', max_length=50)),
                ('feedback_text', models.TextField(help_text='Your feedback (constructive and respectful)')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Submit feedback anonymously (your name will not be shared)')),
                ('is_private', models.BooleanField(default=True, help_text='Keep feedback private (only visible to you and the organisation)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access', models.ForeignKey(blank=True, help_text='Link to the access record (optional, for context)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='clinicians.patientclinicianaccess')),
                ('patient', models.ForeignKey(help_text='The patient providing feedback', on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Healthcare Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
