# Generated by Django 5.2.8 on 2025-11-29 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0003_healthcarefeedback'),
        ('health_records', '0005_workhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveMeasures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(help_text='Date of the objective assessment')),
                ('shoulder_rom_left', models.CharField(blank=True, help_text='Left shoulder ROM', max_length=200)),
                ('shoulder_rom_right', models.CharField(blank=True, help_text='Right shoulder ROM', max_length=200)),
                ('elbow_rom_left', models.CharField(blank=True, help_text='Left elbow ROM', max_length=200)),
                ('elbow_rom_right', models.CharField(blank=True, help_text='Right elbow ROM', max_length=200)),
                ('wrist_rom_left', models.CharField(blank=True, help_text='Left wrist ROM', max_length=200)),
                ('wrist_rom_right', models.CharField(blank=True, help_text='Right wrist ROM', max_length=200)),
                ('hand_rom_left', models.CharField(blank=True, help_text='Left hand ROM', max_length=200)),
                ('hand_rom_right', models.CharField(blank=True, help_text='Right hand ROM', max_length=200)),
                ('hip_rom_left', models.CharField(blank=True, help_text='Left hip ROM', max_length=200)),
                ('hip_rom_right', models.CharField(blank=True, help_text='Right hip ROM', max_length=200)),
                ('knee_rom_left', models.CharField(blank=True, help_text='Left knee ROM', max_length=200)),
                ('knee_rom_right', models.CharField(blank=True, help_text='Right knee ROM', max_length=200)),
                ('ankle_rom_left', models.CharField(blank=True, help_text='Left ankle ROM', max_length=200)),
                ('ankle_rom_right', models.CharField(blank=True, help_text='Right ankle ROM', max_length=200)),
                ('foot_rom_left', models.CharField(blank=True, help_text='Left foot ROM', max_length=200)),
                ('foot_rom_right', models.CharField(blank=True, help_text='Right foot ROM', max_length=200)),
                ('cervical_rom', models.CharField(blank=True, help_text='Cervical spine ROM', max_length=200)),
                ('thoracic_rom', models.CharField(blank=True, help_text='Thoracic spine ROM', max_length=200)),
                ('lumbar_rom', models.CharField(blank=True, help_text='Lumbar spine ROM', max_length=200)),
                ('shoulder_power_left', models.CharField(blank=True, help_text='Left shoulder power', max_length=200)),
                ('shoulder_power_right', models.CharField(blank=True, help_text='Right shoulder power', max_length=200)),
                ('elbow_power_left', models.CharField(blank=True, help_text='Left elbow power', max_length=200)),
                ('elbow_power_right', models.CharField(blank=True, help_text='Right elbow power', max_length=200)),
                ('wrist_power_left', models.CharField(blank=True, help_text='Left wrist power', max_length=200)),
                ('wrist_power_right', models.CharField(blank=True, help_text='Right wrist power', max_length=200)),
                ('grip_power_left', models.CharField(blank=True, help_text='Left grip power', max_length=200)),
                ('grip_power_right', models.CharField(blank=True, help_text='Right grip power', max_length=200)),
                ('hip_power_left', models.CharField(blank=True, help_text='Left hip power', max_length=200)),
                ('hip_power_right', models.CharField(blank=True, help_text='Right hip power', max_length=200)),
                ('knee_power_left', models.CharField(blank=True, help_text='Left knee power', max_length=200)),
                ('knee_power_right', models.CharField(blank=True, help_text='Right knee power', max_length=200)),
                ('ankle_power_left', models.CharField(blank=True, help_text='Left ankle power', max_length=200)),
                ('ankle_power_right', models.CharField(blank=True, help_text='Right ankle power', max_length=200)),
                ('core_power', models.CharField(blank=True, help_text='Core/trunk power', max_length=200)),
                ('additional_notes', models.TextField(blank=True, help_text='Additional objective findings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(help_text='Link to the assessment this objective data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='objective_measures', to='health_records.assessment')),
                ('clinician', models.ForeignKey(help_text='Clinician who performed the assessment', on_delete=django.db.models.deletion.CASCADE, related_name='objective_measures', to='clinicians.clinician')),
            ],
            options={
                'verbose_name_plural': 'Objective Measures',
                'ordering': ['-assessment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicianInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the clinician to invite', max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional message from patient')),
                ('patient', models.ForeignKey(help_text='The patient inviting the clinician', on_delete=django.db.models.deletion.CASCADE, related_name='clinician_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'email')},
            },
        ),
    ]
