# Generated by Django 5.2.8 on 2025-11-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0004_objectivemeasures_clinicianinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='practitioner_code',
            field=models.CharField(blank=True, editable=False, help_text='Unique 5-character alphanumeric code for patients to find this practitioner', max_length=5, null=True, unique=True),
        ),
    ]
