# Generated by Django 5.2.8 on 2025-11-29 16:55

from django.db import migrations
import random
import string


def generate_unique_code(apps, schema_editor):
    """Generate unique codes for existing clinicians"""
    Clinician = apps.get_model('clinicians', 'Clinician')
    
    def generate_code():
        """Generate a random 5-character alphanumeric code"""
        return ''.join(random.choices(string.ascii_uppercase + string.digits, k=5))
    
    for clinician in Clinician.objects.filter(practitioner_code__isnull=True):
        # Generate a unique code
        while True:
            code = generate_code()
            if not Clinician.objects.filter(practitioner_code=code).exists():
                clinician.practitioner_code = code
                clinician.save()
                break


def reverse_migration(apps, schema_editor):
    """Reverse migration - set codes to None"""
    Clinician = apps.get_model('clinicians', 'Clinician')
    Clinician.objects.update(practitioner_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0005_clinician_practitioner_code'),
    ]

    operations = [
        migrations.RunPython(generate_unique_code, reverse_migration),
    ]
