# Generated by Django 5.2.8 on 2025-11-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0006_auto_20251129_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientclinicianaccess',
            name='consent_allergies',
            field=models.BooleanField(default=True, help_text='Consent to share allergies'),
        ),
        migrations.AddField(
            model_name='patientclinicianaccess',
            name='consent_conditions',
            field=models.BooleanField(default=True, help_text='Consent to share conditions'),
        ),
        migrations.AddField(
            model_name='patientclinicianaccess',
            name='consent_emergency_contacts',
            field=models.BooleanField(default=True, help_text='Consent to share emergency contacts'),
        ),
        migrations.AddField(
            model_name='patientclinicianaccess',
            name='consent_feedback',
            field=models.BooleanField(default=True, help_text='Consent to share healthcare feedback'),
        ),
        migrations.AddField(
            model_name='patientclinicianaccess',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='patientclinicianaccess',
            name='consent_medications',
            field=models.BooleanField(default=True, help_text='Consent to share medications'),
        ),
        migrations.AddField(
            model_name='patientclinicianaccess',
            name='consent_personal_info',
            field=models.BooleanField(default=True, help_text='Consent to share personal information'),
        ),
        migrations.AddField(
            model_name='patientclinicianaccess',
            name='consent_symptoms',
            field=models.BooleanField(default=True, help_text='Consent to share symptoms/assessments'),
        ),
        migrations.AddField(
            model_name='patientclinicianaccess',
            name='consent_work_history',
            field=models.BooleanField(default=True, help_text='Consent to share work history'),
        ),
    ]
