# Generated by Django 5.2.8 on 2025-12-19 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0007_patientclinicianaccess_consent_allergies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='registration_body',
            field=models.CharField(blank=True, choices=[('GMC', 'GMC - General Medical Council'), ('NMC', 'NMC - Nursing and Midwifery Council'), ('HCPC', 'HCPC - Health and Care Professions Council'), ('other', 'Other')], help_text='Professional registration body', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clinician',
            name='registration_verified',
            field=models.BooleanField(default=False, help_text='Whether the registration number has been verified'),
        ),
        migrations.AddField(
            model_name='clinician',
            name='registration_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinician',
            name='registration_verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified the registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
